update infra

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -2,27 +2,33 @@ name: IAC
 
 on:
     push:
-      branches: 
-        - main
-      paths: 
-        - terraform/**
+        branches: [ "main" ]
+        paths: ["terraform/**"]
     pull_request:
-      branches: 
-        - main
-      paths: 
-        - terraform/**
+    workflow_dispatch:
+        inputs:
+            action:
+                description: 'Apply or Destroy'
+                required: true
+                default: 'apply'
+                type: choice
+                options:
+                - apply
+                - destroy
 env:
     # credentials for deployment to AWS
     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     # S3 bucket for the terraform state. 
     BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
+    EKS_CLUSTER: quiz-eks
     AWS_REGION: eu-west-3
 
 jobs:
     terraform:
         name: "Apply terraform code changes"
         runs-on: ubuntu-latest
+        environment: production
         defaults:
             run:
                 shell: bash
@@ -56,10 +62,49 @@ jobs:
           if: steps.plan.outcome == 'failure'
           run: exit 1
 
-        - name: Terraform Apply
-          id: apply
-          if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-          run: terraform apply -auto-approve -input=false -parallelism=1 planfile
+        - name: Terraform Action
+          id: apply_destroy
+          run: |
+            if [ "${{ github.event.inputs.action }}" == "apply" ]; then
+              terraform apply -auto-approve -input=false -parallelism=1 planfile
+            elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
+              terraform destroy -auto-approve -input=false -parallelism=1
+            else
+              echo "Invalid action specified."
+              exit 1
+            fi
+
+        - name: Configure AWS Credential
+          uses: aws-actions/configure-aws-credentials@v4
+          with:
+              aws-region: ${{ env.AWS_REGION}}
+              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+
+        - name: Get kube config file 
+          id: getconfig
+          if: steps.apply_destroy.outcome == 'success'
+          run: |
+            if [ "${{ github.event.inputs.action }}" == "apply" ]; then 
+                aws eks update-kubeconfig --region ${{ env.AWS_REGION}} --name ${{ env.EKS_CLUSTER}}
+            elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
+                echo "Skipping aws eks update-kubeconfig after destroying the infrastructure."
+            else
+                echo "Invalid action specified."
+                exit 1
+            fi
+    
+        - name: Install or Remove Ingress Controller
+          if: steps.apply_destroy.outcome == 'success'
+          run: |
+            if [ "${{ github.event.inputs.action }}" == "apply" ]; then
+              kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.3/deploy/static/provider/aws/deploy.yaml
+            elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
+              echo "Skipping Ingress Controller installation after destroying the infrastructure."
+            else
+              echo "Invalid action specified."
+              exit 1
+            fi
 
 
 
