verify kubeconfig

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -80,6 +80,8 @@ jobs:
               aws-region: ${{ env.AWS_REGION}}
               aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
               aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+              role-session-name: GitHubActions
+              role-duration-seconds: 3600
 
         - name: Get kube config file 
           id: getconfig
@@ -93,17 +95,23 @@ jobs:
                 echo "Invalid action specified."
                 exit 1
             fi
+        
+        - name: Print Kubeconfig
+          id: printkubeconfig
+          if: steps.apply_destroy.outcome == 'success'
+          run: cat $(pwd)/kubeconfig
     
         - name: Install or Remove Ingress Controller
           if: steps.apply_destroy.outcome == 'success' && steps.getconfig.outcome == 'success'
           run: |
+            export KUBECONFIG=$(pwd)/kubeconfig
             if [ "${{ github.event.inputs.action }}" == "apply" ]; then
-              kubectl apply --validate=false -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.3/deploy/static/provider/aws/deploy.yaml
+                kubectl apply --validate=false -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.3/deploy/static/provider/aws/deploy.yaml
             elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
-              echo "Skipping Ingress Controller installation after destroying the infrastructure."
+                echo "Skipping Ingress Controller installation after destroying the infrastructure."
             else
-              echo "Invalid action specified."
-              exit 1
+                echo "Invalid action specified."
+                exit 1
             fi
 
 
